name: flutter_polyfill
description: >-
  1:1 implementations of some of the most commonly used objects
  in Flutter, minimally modified for use without Flutter.
version: 0.1.0
homepage: https://github.com/james-alex/flutter_polyfill

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  meta: ^1.3.0
